name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'emergency'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '✅ Tests'
    label: 'test'
  - title: 'Other'
    label: 'workflow', 'other'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed
  
  $CHANGES
exclude-labels:
  - 'chore'

autolabeler:
  - label: enhancement
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: emergency
    branch:
      - '/^hotfix[/-].+/'
  - label: test
    branch:
      - '/^test[/-].+/'
  - label: refactor
    branch:
      - '/^refactor[/-].+/'
  - label: documentation
    branch:
      - '/^doc[/-].+/'
  - label: workflow
    branch:
      - '/^workflow[/-].+/'
      - '/^ci[/-].+/'
      - '/^release[/-].+/'
  - label: other
    branch:
      - '/^.*$/'
